/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrainingRouteImport } from './routes/training'
import { Route as TentangRouteImport } from './routes/tentang'
import { Route as SuksesRouteImport } from './routes/sukses'
import { Route as PortofolioRouteImport } from './routes/portofolio'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as BookRouteImport } from './routes/book'
import { Route as AudioVideoRouteImport } from './routes/audio-video'
import { Route as ArtikelRouteImport } from './routes/artikel'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ArtikelIdRouteImport } from './routes/artikel.$id'
import { Route as AdminTrainingRouteImport } from './routes/admin/training'
import { Route as AdminOrdersRouteImport } from './routes/admin/orders'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminBooksRouteImport } from './routes/admin/books'
import { Route as AdminAudioVideoRouteImport } from './routes/admin/audio-video'
import { Route as AdminArticlesRouteImport } from './routes/admin/articles'

const TrainingRoute = TrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => rootRouteImport,
} as any)
const TentangRoute = TentangRouteImport.update({
  id: '/tentang',
  path: '/tentang',
  getParentRoute: () => rootRouteImport,
} as any)
const SuksesRoute = SuksesRouteImport.update({
  id: '/sukses',
  path: '/sukses',
  getParentRoute: () => rootRouteImport,
} as any)
const PortofolioRoute = PortofolioRouteImport.update({
  id: '/portofolio',
  path: '/portofolio',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const AudioVideoRoute = AudioVideoRouteImport.update({
  id: '/audio-video',
  path: '/audio-video',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtikelRoute = ArtikelRouteImport.update({
  id: '/artikel',
  path: '/artikel',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtikelIdRoute = ArtikelIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ArtikelRoute,
} as any)
const AdminTrainingRoute = AdminTrainingRouteImport.update({
  id: '/admin/training',
  path: '/admin/training',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/admin/orders',
  path: '/admin/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBooksRoute = AdminBooksRouteImport.update({
  id: '/admin/books',
  path: '/admin/books',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAudioVideoRoute = AdminAudioVideoRouteImport.update({
  id: '/admin/audio-video',
  path: '/admin/audio-video',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminArticlesRoute = AdminArticlesRouteImport.update({
  id: '/admin/articles',
  path: '/admin/articles',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/artikel': typeof ArtikelRouteWithChildren
  '/audio-video': typeof AudioVideoRoute
  '/book': typeof BookRoute
  '/checkout': typeof CheckoutRoute
  '/portofolio': typeof PortofolioRoute
  '/sukses': typeof SuksesRoute
  '/tentang': typeof TentangRoute
  '/training': typeof TrainingRoute
  '/admin/articles': typeof AdminArticlesRoute
  '/admin/audio-video': typeof AdminAudioVideoRoute
  '/admin/books': typeof AdminBooksRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/training': typeof AdminTrainingRoute
  '/artikel/$id': typeof ArtikelIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/artikel': typeof ArtikelRouteWithChildren
  '/audio-video': typeof AudioVideoRoute
  '/book': typeof BookRoute
  '/checkout': typeof CheckoutRoute
  '/portofolio': typeof PortofolioRoute
  '/sukses': typeof SuksesRoute
  '/tentang': typeof TentangRoute
  '/training': typeof TrainingRoute
  '/admin/articles': typeof AdminArticlesRoute
  '/admin/audio-video': typeof AdminAudioVideoRoute
  '/admin/books': typeof AdminBooksRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/training': typeof AdminTrainingRoute
  '/artikel/$id': typeof ArtikelIdRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/artikel': typeof ArtikelRouteWithChildren
  '/audio-video': typeof AudioVideoRoute
  '/book': typeof BookRoute
  '/checkout': typeof CheckoutRoute
  '/portofolio': typeof PortofolioRoute
  '/sukses': typeof SuksesRoute
  '/tentang': typeof TentangRoute
  '/training': typeof TrainingRoute
  '/admin/articles': typeof AdminArticlesRoute
  '/admin/audio-video': typeof AdminAudioVideoRoute
  '/admin/books': typeof AdminBooksRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/training': typeof AdminTrainingRoute
  '/artikel/$id': typeof ArtikelIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/artikel'
    | '/audio-video'
    | '/book'
    | '/checkout'
    | '/portofolio'
    | '/sukses'
    | '/tentang'
    | '/training'
    | '/admin/articles'
    | '/admin/audio-video'
    | '/admin/books'
    | '/admin/dashboard'
    | '/admin/orders'
    | '/admin/training'
    | '/artikel/$id'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/artikel'
    | '/audio-video'
    | '/book'
    | '/checkout'
    | '/portofolio'
    | '/sukses'
    | '/tentang'
    | '/training'
    | '/admin/articles'
    | '/admin/audio-video'
    | '/admin/books'
    | '/admin/dashboard'
    | '/admin/orders'
    | '/admin/training'
    | '/artikel/$id'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/artikel'
    | '/audio-video'
    | '/book'
    | '/checkout'
    | '/portofolio'
    | '/sukses'
    | '/tentang'
    | '/training'
    | '/admin/articles'
    | '/admin/audio-video'
    | '/admin/books'
    | '/admin/dashboard'
    | '/admin/orders'
    | '/admin/training'
    | '/artikel/$id'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArtikelRoute: typeof ArtikelRouteWithChildren
  AudioVideoRoute: typeof AudioVideoRoute
  BookRoute: typeof BookRoute
  CheckoutRoute: typeof CheckoutRoute
  PortofolioRoute: typeof PortofolioRoute
  SuksesRoute: typeof SuksesRoute
  TentangRoute: typeof TentangRoute
  TrainingRoute: typeof TrainingRoute
  AdminArticlesRoute: typeof AdminArticlesRoute
  AdminAudioVideoRoute: typeof AdminAudioVideoRoute
  AdminBooksRoute: typeof AdminBooksRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminTrainingRoute: typeof AdminTrainingRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/training': {
      id: '/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof TrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tentang': {
      id: '/tentang'
      path: '/tentang'
      fullPath: '/tentang'
      preLoaderRoute: typeof TentangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sukses': {
      id: '/sukses'
      path: '/sukses'
      fullPath: '/sukses'
      preLoaderRoute: typeof SuksesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portofolio': {
      id: '/portofolio'
      path: '/portofolio'
      fullPath: '/portofolio'
      preLoaderRoute: typeof PortofolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audio-video': {
      id: '/audio-video'
      path: '/audio-video'
      fullPath: '/audio-video'
      preLoaderRoute: typeof AudioVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artikel': {
      id: '/artikel'
      path: '/artikel'
      fullPath: '/artikel'
      preLoaderRoute: typeof ArtikelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artikel/$id': {
      id: '/artikel/$id'
      path: '/$id'
      fullPath: '/artikel/$id'
      preLoaderRoute: typeof ArtikelIdRouteImport
      parentRoute: typeof ArtikelRoute
    }
    '/admin/training': {
      id: '/admin/training'
      path: '/admin/training'
      fullPath: '/admin/training'
      preLoaderRoute: typeof AdminTrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/books': {
      id: '/admin/books'
      path: '/admin/books'
      fullPath: '/admin/books'
      preLoaderRoute: typeof AdminBooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audio-video': {
      id: '/admin/audio-video'
      path: '/admin/audio-video'
      fullPath: '/admin/audio-video'
      preLoaderRoute: typeof AdminAudioVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/articles': {
      id: '/admin/articles'
      path: '/admin/articles'
      fullPath: '/admin/articles'
      preLoaderRoute: typeof AdminArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ArtikelRouteChildren {
  ArtikelIdRoute: typeof ArtikelIdRoute
}

const ArtikelRouteChildren: ArtikelRouteChildren = {
  ArtikelIdRoute: ArtikelIdRoute,
}

const ArtikelRouteWithChildren =
  ArtikelRoute._addFileChildren(ArtikelRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArtikelRoute: ArtikelRouteWithChildren,
  AudioVideoRoute: AudioVideoRoute,
  BookRoute: BookRoute,
  CheckoutRoute: CheckoutRoute,
  PortofolioRoute: PortofolioRoute,
  SuksesRoute: SuksesRoute,
  TentangRoute: TentangRoute,
  TrainingRoute: TrainingRoute,
  AdminArticlesRoute: AdminArticlesRoute,
  AdminAudioVideoRoute: AdminAudioVideoRoute,
  AdminBooksRoute: AdminBooksRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminTrainingRoute: AdminTrainingRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
